<<<<<<< HEAD
name: Deploy to main server (https://yip.cat)
on:
  push:
    branches: [ main ]

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
          - name: Execute remote SSH commands using SSH key
            uses: appleboy/ssh-action@v1
=======
name: test for deploy action
on:
  push:
    branches: [ dev ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: deploy
<<<<<<< HEAD
            uses: appleboy/ssh-action@master
>>>>>>> d2136d9 (add test deploy workflow)
=======
            uses: appleboy/ssh-action@v1
>>>>>>> ff702cf (fix test deploy)
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
<<<<<<< HEAD
                script: ./deploy.sh
=======
                script: whoami
>>>>>>> d2136d9 (add test deploy workflow)
